[package]
name = "ac-qu-ai-nt"
description = "A WIP project using AI to break down a user's query, acquire the knowledge to answer it, then transfer those insights to the user"
version = "0.0.1"
edition = "2021"
rust-version = "1.76"

authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
default = ["cli-clap"]
cli-clap = ["dep:ac-qu-ai-nt-cli-clap"]

[dependencies]
ac-qu-ai-nt-cli-clap = { version = "0.0.1", path = "../cli-clap", optional = true }
