name: Check, build, and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Nextest
        uses: taiki-e/install-action@cargo-nextest

      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --verbose

      - name: Formatting
        run: cargo fmt --check --verbose

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo nextest run

  minimal-dependencies-check-build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-minimal-versions
        uses: taiki-e/install-action@cargo-hack
      - name: Install cargo-minimal-versions
        uses: taiki-e/install-action@cargo-minimal-versions

      - uses: Swatinem/rust-cache@v2

      - name: Check (minimal dependencies)
        run: cargo minimal-versions check --workspace

      - name: Build (minimal dependencies)
        run: cargo minimal-versions build --workspace

      - name: Test (minimal dependencies)
        run: cargo minimal-versions test --workspace
